// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: animal.proto

package animal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_animal_proto_rawDescGZIP(), []int{0}
}

type ColorAnimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Animal string `protobuf:"bytes,1,opt,name=Animal,proto3" json:"Animal,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *ColorAnimal) Reset() {
	*x = ColorAnimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorAnimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorAnimal) ProtoMessage() {}

func (x *ColorAnimal) ProtoReflect() protoreflect.Message {
	mi := &file_animal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorAnimal.ProtoReflect.Descriptor instead.
func (*ColorAnimal) Descriptor() ([]byte, []int) {
	return file_animal_proto_rawDescGZIP(), []int{1}
}

func (x *ColorAnimal) GetAnimal() string {
	if x != nil {
		return x.Animal
	}
	return ""
}

func (x *ColorAnimal) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_animal_proto protoreflect.FileDescriptor

var file_animal_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x48, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x3b, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x32,
	0x3c, 0x0a, 0x03, 0x48, 0x61, 0x74, 0x12, 0x35, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x12, 0x10, 0x2e, 0x48, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x48, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_animal_proto_rawDescOnce sync.Once
	file_animal_proto_rawDescData = file_animal_proto_rawDesc
)

func file_animal_proto_rawDescGZIP() []byte {
	file_animal_proto_rawDescOnce.Do(func() {
		file_animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_animal_proto_rawDescData)
	})
	return file_animal_proto_rawDescData
}

var file_animal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_animal_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: HatServer.Empty
	(*ColorAnimal)(nil), // 1: HatServer.ColorAnimal
}
var file_animal_proto_depIdxs = []int32{
	0, // 0: HatServer.Hat.GetAnimal:input_type -> HatServer.Empty
	1, // 1: HatServer.Hat.GetAnimal:output_type -> HatServer.ColorAnimal
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_animal_proto_init() }
func file_animal_proto_init() {
	if File_animal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_animal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_animal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorAnimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_animal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_animal_proto_goTypes,
		DependencyIndexes: file_animal_proto_depIdxs,
		MessageInfos:      file_animal_proto_msgTypes,
	}.Build()
	File_animal_proto = out.File
	file_animal_proto_rawDesc = nil
	file_animal_proto_goTypes = nil
	file_animal_proto_depIdxs = nil
}
