// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: animal.proto

package animal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Hat_GetAnimal_FullMethodName = "/HatServer.Hat/GetAnimal"
)

// HatClient is the client API for Hat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HatClient interface {
	GetAnimal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ColorAnimal, error)
}

type hatClient struct {
	cc grpc.ClientConnInterface
}

func NewHatClient(cc grpc.ClientConnInterface) HatClient {
	return &hatClient{cc}
}

func (c *hatClient) GetAnimal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ColorAnimal, error) {
	out := new(ColorAnimal)
	err := c.cc.Invoke(ctx, Hat_GetAnimal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HatServer is the server API for Hat service.
// All implementations must embed UnimplementedHatServer
// for forward compatibility
type HatServer interface {
	GetAnimal(context.Context, *Empty) (*ColorAnimal, error)
	mustEmbedUnimplementedHatServer()
}

// UnimplementedHatServer must be embedded to have forward compatible implementations.
type UnimplementedHatServer struct {
}

func (UnimplementedHatServer) GetAnimal(context.Context, *Empty) (*ColorAnimal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimal not implemented")
}
func (UnimplementedHatServer) mustEmbedUnimplementedHatServer() {}

// UnsafeHatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HatServer will
// result in compilation errors.
type UnsafeHatServer interface {
	mustEmbedUnimplementedHatServer()
}

func RegisterHatServer(s grpc.ServiceRegistrar, srv HatServer) {
	s.RegisterService(&Hat_ServiceDesc, srv)
}

func _Hat_GetAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HatServer).GetAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hat_GetAnimal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HatServer).GetAnimal(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Hat_ServiceDesc is the grpc.ServiceDesc for Hat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HatServer.Hat",
	HandlerType: (*HatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimal",
			Handler:    _Hat_GetAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "animal.proto",
}
